export const userdatakey = 'idcan-userdata'
export const filterStateKey = 'idcan-filterstate'
export const messageStateKey = 'idcan-messagestate'
export const inscriptionStateKey = 'idcan-inscription'
export const eventMessageStateKey = 'idcan-eventmessage'
export const localStorageTabKey = 'idcan-uniquetab'
export const inscriptionFinalStateKey = 'idcan-inscription-final'
